---
- name: Install storage utils packages
  become: yes
  become_method: sudo
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ storage_packages }}"

- name: Install scsi packages
  become: yes
  become_method: sudo
  apt:
    name: "sg3-utils"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install scsi packages
  become: yes
  become_method: sudo
  yum:
    name: "sg3_utils"
    state: present
  when: ansible_os_family == 'RedHat'
