---
- hosts: all
  any_errors_fatal: yes
  pre_tasks:
    - name: Install lvm package
      yum:
        name: "lvm2"
        state: present
    - name: Change lvm configuration
      lineinfile:
        path: /etc/lvm/lvm.conf
        regexp: '^.*udev_rules \='
        line: ' udev_rules = 0'
    - name: Get loopback device
      shell: "losetup -l | awk '/lvmtest.{{ loop_id }}.img/ {print $1}'"
      changed_when: false
      register: lvm_losetup
      tags:
        - skip_ansible_lint
    - name: Prepare image disk
      command: 'dd if=/dev/zero of=lvmtest{{ loop_id }}.img bs=200 count=1M'
      when: lvm_losetup.stdout != "/dev/loop{{ loop_id }}"
    - name: Prepare lvm inside container
      command: 'losetup /dev/loop{{ loop_id }} lvmtest{{ loop_id }}.img'
      when: lvm_losetup.stdout != "/dev/loop{{ loop_id }}"
  roles:
    - ansible-role-storage-init
