---
lvm_vgs:
  - name: test
    disks:
      - /dev/loop0

lvm_volumes:
  - name: test
    vg: test
    size: 52M
    fstype: xfs
    path: "/var/lib/docker"
    opts: "-n ftype=1"
  - name: test2
    vg: test
    size: 20M
    fstype: xfs
    path: "/var/lib/test2"
